### PR TITLE
Test with latest Django

### PR DESCRIPTION
**Pull request by Matusf**

### CODE REVIEW

**Comment by ricco386** [comment]
@Matusf will you have a chance to update this PR?

**Comment by Matusf** [comment]
I'll try to do it today or tomorrow if you don't mind.

2016-11-15 21:01 GMT+01:00 Richard Kellner <notifications@github.com>:

**Comment by ricco386** [comment]
@Matusf sure no problem

**Comment by ricco386** [comment]
@Matusf thank you.

**Pull request merged**
