### PR TITLE
#17_Show_event_details_view

### PR DESCRIPTION
**Pull request by TomasHo**
add event_details view  + basic template

### CODE REVIEW

**Comment by ZoltanOnody** [comment]
Please rebase your project so there aren't 11 commits (9 already merged) in PR.

**Comment by ricco386** [comment]
I have explained it in CONTRIBUTING.rst, but probably should be more specific... To avaoid sytuations like this you should do following:

0. You create a fork of the project (you do this only once, and you already have it,it is your repo in which you are working)
1. You pick up a issue, and make a comment that you are working on it
2. in your local git copy you create a branch: `git checkout -b XX-new-feature` (where XX is issue number)
3. you do the work:
  * you can commit how many time you want
  * you can push to server how many times you want `git push origin XX-new-feature`
  * you can also pull from upstream how many times you want (at this point we dont care about merge message, or rebase to get rid of it as we will do squish merge -> in upstream master it will looks like one commit)
4. once you are ready you click on pull request button, and select master branch in upstream and XX-new-feature branch from your repo. 
  * if reviewer asks for changes you can do all the things mentioned in point 3
  * Once happy with the changes make a note in PR to review again
5. your feature is approved and merged to master of upstream, so you can check out master at your local copy: `git checkout master` and pull the newly approved changes from upstream `git pull upstream master`
6. once done you work in branch came to your master from upstream as a one commit and you can delete your local branch `git branch --delete XX-new-feature`

**Comment by ricco386** [comment]
Just to explain what has happend (it also happend to me and @ZoltanOnody couple of days ago)...

You are working in master branch of your fork, and you do multiple commits to fix an issue and once you request PR, it is reviewed and squashed merged into master of upstream repo.

Resul of this action is that in upstream master all your code is there, but it went there from a single commit, however your local copy has all the code but it is in several commits and when trying to pull from upstream you are downloading the same code but from one (different commit) that makes git confused, as a result in this PR there is code, that was already approved and merged into master of upstream.

It is possible to fix in cmd line of git, but my guess is that the quickest way for you is to delete the fork on github and create a new one, same on you local machine. Otherwise you need to fech the upstream code, do the rebase (where will be conflicts, resolve them) and force push to your fork on github.

**Comment by TomasHo** [comment]
PR can be discarded.

**Pull request closed without merging**
