### PR TITLE
run flake8 before_script

### PR DESCRIPTION
**Pull request by ZoltanOnody**
we are expecting failure

### CODE REVIEW

**Comment by ricco386** [comment]
or better use before_install (this might not even install if there is problem with pep8) instead of before_script.

Or we can update existing include scrip and test pep8 as part of LTS test, but I guess if we set extra env: TEST_PEP8=True it would be clear directly from the test...

**Comment by ZoltanOnody** [comment]
It seems to be working but I'll try one more thing

**Comment by ricco386** [comment]
seems working, however I am wondering if it will also work if the PEP8 is ok? Just curious if it doesnt crash during the Django install since it is not specified in envs...?

**Comment by ZoltanOnody** [comment]
It seems to be working :)

**Pull request merged**
