### PR TITLE
Discount Codes model

### PR DESCRIPTION
**Pull request by TomasHo**

### CODE REVIEW

**Comment by ricco386** [comment]
Unfortunately there has been another merge request done before this which caused conflict. Please pull the changes from upstream and fix the conflict.

If you leave your code at the end of the file, leave last line blank, so the code is according to [PEP8](https://www.python.org/dev/peps/pep-0008)

**Comment by TomasHo** [comment]
Issues fixed, discount types added.

**Comment by ricco386** [comment]
@TomasHo did you commit correct version? it seems you have removed the class at all, commit 6ea846526d is removing whole class DiscountCodes(models.Model)

**Comment by TomasHo** [comment]
Sorry, should be ok now.

**Comment by ricco386** [comment]
@TomasHo sure thanks, merging the code into upstream.

For the future at the end of the file, leave last line blank, so the code is according to [PEP8](https://www.python.org/dev/peps/pep-0008)

**Pull request merged**
